name: zeytin_local_storage
description: Zeytin is a database solution developed with care and love for server and local solutions.
version: 1.1.1
repository: https://github.com/JeaFrid/ZeytinLocalStorage
homepage: https://github.com/JeaFrid/ZeytinLocalStorage
issue_tracker: https://github.com/JeaFrid/ZeytinLocalStorage/issues

environment:
  sdk: ^3.0.0

dependencies:
  encrypt: ^5.0.3
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
