name: zeytin_local_storage
description: Zeytin is a database solution developed with care and love for server and local solutions.
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.8

dependencies:
  encrypt: ^5.0.3
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
